"""
PyMOL Export Module for All-Atom Visualization

Generates self-contained PyMOL Python scripts for visualizing
molecular interactions.

The generated script follows the same approach as the main PLIP:
1. Loads the PDB structure
2. Creates atom objects by PDB index using cmd.create()
3. Creates distance measurement objects using cmd.distance()
4. Groups interactions by type and spatial category with distinct styling
5. Organizes everything into PyMOL groups for easy toggling
"""

from collections import defaultdict
from typing import Any, Dict, List, Optional, Tuple

INTERACTION_STYLES: Dict[str, Dict[str, Any]] = {
    'hbond': {
        'label': 'Hydrogen Bonds',
        'color': (0, 102, 204),
    },
    'hbond_possible': {
        'label': 'Possible H-Bonds',
        'color': (153, 204, 255),
    },
    'saltbridge': {
        'label': 'Salt Bridges',
        'color': (255, 204, 0),
    },
    'hydrophobic': {
        'label': 'Hydrophobic Contacts',
        'color': (128, 128, 128),
    },
    'pistacking': {
        'label': 'Pi-Stacking',
        'color': (0, 153, 0),
    },
    'pication': {
        'label': 'Pi-Cation',
        'color': (255, 102, 0),
    },
    'halogen': {
        'label': 'Halogen Bonds',
        'color': (0, 204, 204),
    },
    'water_bridge': {
        'label': 'Water Bridges',
        'color': (153, 204, 255),
    },
    'metal': {
        'label': 'Metal Coordination',
        'color': (153, 0, 204),
    },
}


def _classify_category(res_a_chain: str, res_a_num: int,
                       res_b_chain: str, res_b_num: int) -> str:
    if res_a_chain != res_b_chain:
        return 'cross'
    elif res_a_num != res_b_num:
        return 'inter'
    else:
        return 'intra'


def _dash_params(category: str) -> Tuple[float, float, float]:
    params = {
        'intra': (0.5, 0.3, 0.05),
        'inter': (0.0, 0.0, 0.05),
        'cross': (0.0, 0.0, 0.08),
    }
    return params.get(category, (0.0, 0.0, 0.05))


def _rgb_to_hex(r: int, g: int, b: int) -> str:
    return f'#{r:02x}{g:02x}{b:02x}'


def _needs_pseudoatom(interaction) -> bool:
    return (interaction.atom_a_name == 'RING' or
            interaction.atom_b_name == 'RING')


def _get_ring_coords(interaction, atom_coords):
    coords_a = None
    coords_b = None
    if interaction.atom_a_name == 'RING' and interaction.details:
        coords_a = interaction.details.get('ring_center')
        if coords_a is None and 'ring_a_atoms' in interaction.details:
            ring_atoms = interaction.details['ring_a_atoms']
            ring_coords = [
                atom_coords[idx] for idx in ring_atoms
                if idx in atom_coords
            ]
            if ring_coords:
                coords_a = [sum(c[i] for c in ring_coords) / len(ring_coords)
                            for i in range(3)]
    else:
        coords_a = atom_coords.get(interaction.atom_a_idx)
    if interaction.atom_b_name == 'RING' and interaction.details:
        coords_b = interaction.details.get('ring_center')
        if coords_b is None and 'ring_b_atoms' in interaction.details:
            ring_atoms = interaction.details['ring_b_atoms']
            ring_coords = [
                atom_coords[idx] for idx in ring_atoms
                if idx in atom_coords
            ]
            if ring_coords:
                coords_b = [sum(c[i] for c in ring_coords) / len(ring_coords)
                            for i in range(3)]
    else:
        coords_b = atom_coords.get(interaction.atom_b_idx)
    return coords_a, coords_b


def _generate_header() -> List[str]:
    return [
        '#',
        '# PyMOL Script - Generated by All-Atom Visualization',
        '# ============================================================',
        '#',
        '# Usage:',
        '#   PyMOL GUI:  File > Run > select this file',
        '#   Terminal:   pymol -c this_file.py',
        '#   PyMOL CLI:  run /path/to/this_file.py',
        '#',
        '# Customization:',
        '#   - Colors:    Edit RGB values in set_color() calls below',
        '#   - Dashes:    Adjust dash_gap / dash_radius per group',
        '#   - Toggle:    Use the PyMOL object panel to show/hide groups',
        '#   - Labels:    Labels show distance per interaction',
        '#',
        '# ============================================================',
        '#',
        'from pymol import cmd',
        '',
    ]


def _generate_structure_loading(pdb_path: Optional[str],
                                 pdb_content: Optional[str]) -> List[str]:
    lines = [
        '#',
        '# ============================================================',
        '# SECTION 1: Load Structure',
        '# ============================================================',
        '# The structure is loaded as object "structure".',
        '# All atom selections use PDB atom indices (id N).',
        '#',
    ]
    if pdb_path:
        lines.append(f'cmd.load(r\'{pdb_path}\', \'structure\')')
    elif pdb_content:
        lines.extend([
            'cmd.read_pdbstr(\'\'\'\\',
            pdb_content,
            '\'\'\', \'structure\')',
        ])
    else:
        lines.append('# NO STRUCTURE - load manually with cmd.load()')
    lines.append('')
    return lines


def _generate_settings() -> List[str]:
    return [
        '#',
        '# ============================================================',
        '# SECTION 2: General Settings',
        '# ============================================================',
        '#',
        'cmd.set(\'bg_rgb\', [1.0, 1.0, 1.0])',
        'cmd.set(\'depth_cue\', 0)',
        'cmd.set(\'dash_radius\', 0.05)',
        'cmd.set(\'dash_transparency\', 0.3)',
        '',
    ]


def _generate_color_definitions() -> List[str]:
    lines = [
        '#',
        '# ============================================================',
        '# SECTION 3: Custom Color Definitions',
        '# ============================================================',
        '# Edit RGB values (0-255) to change interaction colors.',
        '#',
    ]
    for inter_type, style in INTERACTION_STYLES.items():
        r, g, b = style['color']
        lines.append(
            f"cmd.set_color('color_{inter_type}', '[{r}, {g}, {b}]')"
        )
    lines.append('')
    return lines


def _generate_interaction_visualizations(
    interactions: List,
    atom_coords: Dict[int, List[float]],
) -> List[str]:
    lines = [
        '#',
        '# ============================================================',
        '# SECTION 4: Interaction Visualizations',
        '# ============================================================',
        '#',
        '# Each interaction is an individual group containing its distance',
        '# object and residue selections. Groups are nested by type under',
        '# the "Interactions" master group for hierarchical toggling.',
        '# Use the PyMOL object panel to expand/collapse groups.',
        '#',
    ]

    by_type = defaultdict(list)
    for interaction in interactions:
        by_type[interaction.type].append(interaction)

    type_group_names = []

    for inter_type in sorted(by_type.keys()):
        type_interactions = by_type[inter_type]
        style = INTERACTION_STYLES.get(inter_type, {
            'label': inter_type.replace('_', ' ').title(),
            'color': (200, 200, 200),
        })

        lines.append('')
        lines.append(f'# --- {style["label"]} ---')

        individual_group_names = []

        for i, interaction in enumerate(type_interactions):
            category = _classify_category(
                interaction.res_a_chain, interaction.res_a_num,
                interaction.res_b_chain, interaction.res_b_num,
            )
            dash_gap, _, dash_radius = _dash_params(category)

            dist_name = f'{inter_type}_{i}'
            grp_name = f'{inter_type}_{i}_grp'
            sel_a = f'sel_{inter_type}_{i}_a'
            sel_b = f'sel_{inter_type}_{i}_b'

            # Create residue atom objects (using create instead of select
            # so they appear in the object panel and can be grouped)
            if _needs_pseudoatom(interaction):
                coords_a, coords_b = _get_ring_coords(
                    interaction, atom_coords)
                if coords_a:
                    lines.append(
                        f'cmd.pseudoatom(\'{sel_a}\', '
                        f'pos=[{coords_a[0]:.3f}, {coords_a[1]:.3f}, '
                        f'{coords_a[2]:.3f}])')
                else:
                    lines.append(
                        f'cmd.create(\'{sel_a}\', '
                        f'\'id {interaction.atom_a_idx}\')')
                if coords_b:
                    lines.append(
                        f'cmd.pseudoatom(\'{sel_b}\', '
                        f'pos=[{coords_b[0]:.3f}, {coords_b[1]:.3f}, '
                        f'{coords_b[2]:.3f}])')
                else:
                    lines.append(
                        f'cmd.create(\'{sel_b}\', '
                        f'\'id {interaction.atom_b_idx}\')')
            else:
                lines.append(
                    f'cmd.create(\'{sel_a}\', '
                    f'\'id {interaction.atom_a_idx}\')')
                lines.append(
                    f'cmd.create(\'{sel_b}\', '
                    f'\'id {interaction.atom_b_idx}\')')

            # Create individual distance object
            lines.append(
                f'cmd.distance(\'{dist_name}\', '
                f'\'{sel_a}\', \'{sel_b}\')')

            # Apply category-specific styling
            if dash_gap > 0:
                lines.append(
                    f'cmd.set(\'dash_gap\', {dash_gap}, '
                    f'\'{dist_name}\')')
            if dash_radius != 0.05:
                lines.append(
                    f'cmd.set(\'dash_radius\', {dash_radius}, '
                    f'\'{dist_name}\')')
            lines.append(
                f'cmd.set(\'dash_color\', \'color_{inter_type}\', '
                f'\'{dist_name}\')')

            # Add distance label
            lines.append(
                f'cmd.label(\'{sel_a}\', '
                f'\'\"Distance: {interaction.distance:.2f} Å\"\')')

            # Group this individual interaction (selections + distance)
            lines.append(
                f'cmd.group(\'{grp_name}\', '
                f'\'{sel_a} {sel_b} {dist_name}\')')

            individual_group_names.append(grp_name)
            lines.append('')

        # Group all individual interaction groups under this type
        if individual_group_names:
            members_str = ' '.join(individual_group_names)
            lines.append(
                f'cmd.group(\'{inter_type}\', \'{members_str}\')')
            type_group_names.append(inter_type)

        lines.append('')

    # Group all types under Interactions master group
    if type_group_names:
        members_str = ' '.join(type_group_names)
        lines.extend([
            '# Group all interaction types under master group',
            f'cmd.group(\'Interactions\', \'{members_str}\')',
            '',
        ])

    return lines


def _generate_cleanup() -> List[str]:
    return [
        '#',
        '# ============================================================',
        '# SECTION 5: Hide Temporary Atom Objects',
        '# ============================================================',
        '# Hide sel_* objects to avoid visual duplication in 3D view.',
        '# They remain in the object panel for hierarchical grouping.',
        '# Uncomment the delete line to remove them entirely.',
        '#',
        'cmd.hide(\'everything\', \'sel_*\')',
        '# cmd.delete(\'sel_*\')',
        '',
    ]


def _generate_residue_colors(
    residue_colors: Dict[str, List[int]]
) -> List[str]:
    lines = [
        '#',
        '# ============================================================',
        '# SECTION 6: Custom Residue Colors',
        '# ============================================================',
        '# Colors from the web interface residue pickers.',
        '# Format: cmd.color("hex", "resi NUM and chain CHAIN")',
        '#',
    ]
    for res_key, color in residue_colors.items():
        parts = res_key.split(':')
        if len(parts) == 2:
            chain, res_num = parts
            if isinstance(color, (list, tuple)) and len(color) == 3:
                hex_color = _rgb_to_hex(
                    int(color[0]), int(color[1]), int(color[2]))
                lines.append(
                    f'cmd.color(\'{hex_color}\', '
                    f'\'resi {res_num} and chain {chain}\')')
    lines.append('')
    return lines


def _generate_final_adjustments() -> List[str]:
    return [
        '#',
        '# ============================================================',
        '# SECTION 7: Final Adjustments',
        '# ============================================================',
        '#',
        '# Show cartoon + sticks for the structure',
        'cmd.show(\'cartoon\', \'structure\')',
        'cmd.show(\'sticks\', \'structure\')',
        '',
        '# Highlight residues involved in interactions',
        '# Uncomment to show sticks for interacting residues:',
        '# cmd.select(\'InteractingResidues\', '
        '\'byres (structure)\')',
        '# cmd.show(\'sticks\', \'InteractingResidues\')',
        '',
        'cmd.deselect()',
        'cmd.zoom()',
        '',
        '#',
        '# ============================================================',
        '# END OF SCRIPT',
        '# ============================================================',
        '#',
        '# Post-processing examples:',
        '#   cmd.ray(1200, 800)',
        '#   cmd.png(\'output.png\')',
        '#   cmd.save(\'output.pse\')',
        '#',
    ]


def generate_pymol_script(
    interactions: List,
    atom_coords: Dict[int, List[float]],
    pdb_path: Optional[str] = None,
    pdb_content: Optional[str] = None,
    residue_colors: Optional[Dict[str, List[int]]] = None,
) -> str:
    """
    Generate a complete PyMOL Python script for visualizing interactions.

    Uses the same approach as the main PLIP:
    - cmd.create('name', 'id N') to create atom objects by PDB index
    - cmd.distance('ObjName', 'sel1', 'sel2') to create distance objects
    - cmd.pseudoatom() only for ring centers (pi-stacking, cation-pi)
    - cmd.group() to organize distance objects by type
    - cmd.hide('everything', '_sel_*') to hide atom objects in 3D view

    Args:
        interactions: List of interaction objects
        atom_coords: Dict mapping atom index to [x, y, z] coordinates
        pdb_path: Path to PDB file
        pdb_content: PDB content string (used if pdb_path is None)
        residue_colors: Custom residue colors {"chain:resNum": [r, g, b]}

    Returns:
        Complete PyMOL Python script as a string
    """
    lines = []
    lines.extend(_generate_header())
    lines.extend(_generate_structure_loading(pdb_path, pdb_content))
    lines.extend(_generate_settings())
    lines.extend(_generate_color_definitions())
    lines.extend(_generate_interaction_visualizations(interactions, atom_coords))
    lines.extend(_generate_cleanup())
    if residue_colors:
        lines.extend(_generate_residue_colors(residue_colors))
    lines.extend(_generate_final_adjustments())
    return '\n'.join(lines)